config/routes.rb
Rails.application.routes.draw do
  root 'topics#index'
  get 'topics/index'
  get 'topics/show/:id' => 'topics#show', as: :topics_show
  post 'topics/create' => 'topics#create'
  post 'posts/create' => 'post#create', as: :post_create
  post 'topics/update/:id' => 'topics#update'
  delete 'posts/delete/:id' => 'post#delete', as: :post_delete
  delete 'topics/delete/:id' => 'topics#delete', as: :topic_delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/post_controller.rb
class PostController < ApplicationController
    def create
        @post = Post.new(params[:post].permit(:topic_id, :name, :res, :body))
        @post.save
        redirect_to topics_show_path(params[:post]['topic_id'])
    end

    def delete
        @post = Post.find(params[:id])
        id = @post.topic_id
        @post.destroy
        redirect_to topics_show_path(id)
    end
        
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
    @newTopic = Topic.new
  end

  def create
    @topic = Topic.new(params[:topic].permit(:title))
    @topic.save
    redirect_to topics_index_path
  end

  def delete
    @topic = Topic.find(params[:id])
    @post = Post.where(topic_id: params[:id])
    @post.destroy_all
    @topic.destroy
    redirect_to topics_index_path
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.update(title: params[:title])
    redirect_to topics_index_path
  end

  def show
    @topic = Topic.find(params[:id])
    @newpost = Post.new(:topic_id => params[:id])
    @posts = Post.where(topic_id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/topics/index.html.erb
<h1>スレッド一覧</h1>

<%= form_for @newTopic, :url => {:action => 'create'} do |f| %>
  <%= f.text_field :title %>
  <%= f.submit "新規作成" %>
<% end %>
<ul>
  <% @topics.each do |topic| %>
    <li>
    <h3>
      <%= link_to topic.title, topics_show_path(topic.id) %>
      <%= link_to '[削除]', topic_delete_path(topic.id), method: :delete, data: {confirm: "削除してもよろしいですか？"} %>
    </h3>
    <h5>
      <%= form_tag("/topics/update/#{topic.id}") do %>
      <form>
        <label>編集 :</label>
        <input type="text" name="title">
        <!--form-group-->
        <button type="submit">実行</button>
      <% end %>
    </h5>
    </li>
  <% end %>
</ul>

app/views/topics/show.html.erb
<h1><%= link_to "Index", root_path %></h1>

<h1><%= @topic.title %></h1>
<% @posts.each do |post| %>
  <p>
    <% if post.res == nil %>
    <% else %>
      (*<%= post.res %>)
    <% end%>
    <%= post.name %> : <%= post.body %>
    <%= link_to '[削除]', post_delete_path(post.id), method: :delete, data: {confirm: "削除してもよろしいですか？"} %>
<% end %>
</p>

<br><br><br>

<h3>---投稿---</h3>
<%= form_for @newpost, :url => post_create_path do |f| %>
  <p>ユーザ</p>
  <p><%= f.text_field :name %></p>
  <p>返信</p>
  <%= f.select :res, Post.all.map { |post| [post.name] }, include_blank:true %>
  <p>コメント</p>
  <p><%= f.text_area :body %></p>
  <%= f.hidden_field :topic_id %>
  <%= f.submit "send"%>
<% end %>